### PR TITLE
Demonstrate activity source usage

### PR DESCRIPTION
**Pull request by kamleshplayerzero**
Activity source added in application to help demonstrate more advanced concepts like customization of the tracestate attributes during authentication.

- - -
This change is [Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2)

### CODE REVIEW

**Review by sepatel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2)* status: all files reviewed, 1 unresolved discussion (waiting on @kamleshplayerzero)

___
*[`aspdotnet/Program.cs` line 76 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2#-O0QzVgZ3wrGOjitP6rH:-O0QzVgZ3wrGOjitP6rI:bsop25g) ([raw file](https://github.com/goplayerzero/open-telemetry-dotnet/blob/a61df4c07972a29add7e2f295f66e346c7f37124/aspdotnet/Program.cs#L76)):*
> ```Smalltalk
> string HandleRollDice([FromServices]ILogger<Program> logger, string? player)
> {
>     using var activity = p0ActivitySource.StartActivity("ActivityName");
> ```

I don't think we really want to be encouraging people to be manually wrapping all their calls with custom spans. This PR doesn't seem like the right solution to solving the problem. It is good readme type info and perhaps a second/different method to demonstrate more advanced capabilities but not really idea for the simple hello world demonstration.

**Review by kamleshplayerzero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @sepatel)

___
*[`aspdotnet/Program.cs` line 76 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2#-O0QzVgZ3wrGOjitP6rH:-O0TSbuE44kD8JInkmsr:bg355eo) ([raw file](https://github.com/goplayerzero/open-telemetry-dotnet/blob/a61df4c07972a29add7e2f295f66e346c7f37124/aspdotnet/Program.cs#L76)):*
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

I don't think we really want to be encouraging people to be manually wrapping all their calls with custom spans. This PR doesn't seem like the right solution to solving the problem. It is good readme type info and perhaps a second/different method to demonstrate more advanced capabilities but not really idea for the simple hello world demonstration.
</blockquote></details>

Yes,
Added it in AuthController now

**Review by sepatel — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2)* status: all files reviewed, 1 unresolved discussion (waiting on @kamleshplayerzero)

___
*[`aspdotnet/Program.cs` line 13 at r2](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2#-O0WlFzY6DyIh_fvh4jI:-O0WlFzY6DyIh_fvh4jJ:b-806hm0) ([raw file](https://github.com/goplayerzero/open-telemetry-dotnet/blob/f016f2f1fe194e013c679fe99d0fcf2c7bf816cb/aspdotnet/Program.cs#L13)):*
> ```Smalltalk
> var builder = WebApplication.CreateBuilder(args);
> 
> const string serviceName = "June28.ActivitySource";
> ```

Don't forget to put back to original readme style code content not test code values

**Review by kamleshplayerzero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @sepatel)

___
*[`aspdotnet/Program.cs` line 13 at r2](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2#-O0WlFzY6DyIh_fvh4jI:-O0njXXdCLTQaiUvxA6M:b-896fix) ([raw file](https://github.com/goplayerzero/open-telemetry-dotnet/blob/f016f2f1fe194e013c679fe99d0fcf2c7bf816cb/aspdotnet/Program.cs#L13)):*
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

Don't forget to put back to original readme style code content not test code values
</blockquote></details>

Done.

**Review by sepatel — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kamleshplayerzero)

**Pull request merged**
